
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-happycows-f25-15
owner: ucsb-cs156-f25
repo_name: proj-happycows-f25-15
pull_requests: [{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"ggCommonsFeatures","number":29,"title":"gg added storybook for commons features","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/29"},{"author":{"id":"U_kgDOBpYh_w","is_bot":false,"login":"Shibainuinuinu","name":"Kelvin Fang"},"headRefName":"Kelvin-CRUD-courses","number":28,"title":"Added CRUD operations for Courses and Tests","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/28"},{"author":{"id":"U_kgDOB3B5Cw","is_bot":false,"login":"novuxx888","name":"Andrew Xiong"},"headRefName":"main_mutation_errors","number":19,"title":"fixed mutation errors from main caused by flaky tests","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/19"},{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"ggCommonCase","number":17,"title":"Gg common case","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/17"},{"author":{"id":"U_kgDOCL5eCw","is_bot":false,"login":"timmywin","name":"tim"},"headRefName":"tvn-UI-launch-RecordCommonStats","number":16,"title":"Tvn UI launch record common stats","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/16"},{"author":{"id":"U_kgDOB3B5Cw","is_bot":false,"login":"novuxx888","name":"Andrew Xiong"},"headRefName":"ux_redesign","number":13,"title":"redesigned ux in separate file and added tests","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/13"},{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"ggWireMock","number":10,"title":"Gg wire mock","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/10"}]
